default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: csskitchen
  #password: <%= Rails.application.credentials.dig(:csskitchen, :database_password) %>
  url: <%= Rails.application.credentials.dig(:csskitchen, :database_url) %>

development:
  <<: *default
  database: csskitchen_development

test:
  <<: *default
  database: csskitchen_test

production:
  <<: *default
  database: csskitchen
  url: <%= ENV["INTERNAL_DATABASE_URL"] %> # Available on Render's environment variables, not necessary locally.
